#!/usr/bin/env bash
#SBATCH -J create-res
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --time=00:10:00
#SBATCH --output=slurm/stdout/create-%A-%a.out
#SBATCH --mail-type=END
#SBATCH --mail-user=nathan.trouvain@inria.fr

set -e

echo "Loading modules"
module load language/python/3.9.6

echo "=========Python setup========="
echo "python : $(python3 --version), $(which python3)"
echo "pip    : $(pip3 --version), $(which pip3)"

echo "venv activation"
source ./venv/bin/activate

echo "(venv) python : $(python3 --version), $(which python3)"
echo "(venv) pip    : $(pip3 --version), $(which pip3)"

srun python3 optimize_decoder.py create_reservoirs \
  --n_instances 30 \
  --instance_dir /beegfs/ntrouvai/canarygan/reservoirs \

