#!/usr/bin/env bash
#SBATCH -J decoder-score
#SBATCH --constraint="a100|v100|p100"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=12
#SBATCH --array=17-20
#SBATCH --time=24:00:00
#SBATCH --output=slurm/stdout/decoderscore_%A-%a.out
#SBATCH --mail-type=END
#SBATCH --mail-user=nathan.trouvain@inria.fr

set -e

echo "Loading modules"
module load compiler/cuda/11.7
module load language/python/3.9.6

echo "==========CUDA info==========="
echo "CUDA info (from nvcc output)"
nvcc --version

echo "=========Python setup========="
echo "python : $(python3 --version), $(which python3)"
echo "pip    : $(pip3 --version), $(which pip3)"

echo "venv activation"
source ./venv/bin/activate

echo "(venv) python : $(python3 --version), $(which python3)"
echo "(venv) pip    : $(pip3 --version), $(which pip3)"

echo "======PyTorch GPU status======"
for i in `seq 1 $SLURM_JOB_NUM_NODES`; do
    srun -N1 -n1 python3 ./slurm/probegpu.py &
done
wait

t=$((SLURM_ARRAY_TASK_ID))

for i in `seq 0 1`; do
    srun -n1 -c12 --exclusive python compute_decoder_scores.py \
        --decoder_ckpt /beegfs/ntrouvai/canarygan/decoder/results/checkpoints/decoder-9.pkl \
        --generator_version "/beegfs/ntrouvai/canarygan/checkpoints/version_$(($t+$i))" \
        --save_dir /beegfs/ntrouvai/canarygan/decoded_gan \
        --n_is_split 10 \
        --batch_size 1000 \
        -c "$SLURM_CPUS_PER_TASK" \
        --device_idx $i \
        &
done
wait

echo "Done !"
