#!/usr/bin/env bash
#SBATCH -J inception-score
#SBATCH --constraint="a100|v100|p100"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=8
#SBATCH --array=0-9
#SBATCH --exclusive
#SBATCH --time=01:00:00
#SBATCH --output=slurm/stdout/inceptionscore_%A-%a.out
#SBATCH --mail-type=END
#SBATCH --mail-user=nathan.trouvain@inria.fr

set -e

echo "Loading modules"
module load compiler/cuda/11.7
module load language/python/3.9.6

echo "==========CUDA info==========="
echo "CUDA info (from nvcc output)"
nvcc --version

echo "=========Python setup========="
echo "python : $(python3 --version), $(which python3)"
echo "pip    : $(pip3 --version), $(which pip3)"

echo "venv activation"
source ./venv/bin/activate

echo "(venv) python : $(python3 --version), $(which python3)"
echo "(venv) pip    : $(pip3 --version), $(which pip3)"

srun python compute_inception.py gan \
    --scorer_ckpt /beegfs/ntrouvai/canarygan/inception/checkpoints/version_0/top5/top_epoch_629-step_15750-loss_0.000-val_acc_0.99.ckpt \
    --generator_version "/beegfs/ntrouvai/canarygan/checkpoints/version_$SLURM_ARRAY_TASK_ID" \
    --out_dir /beegfs/ntrouvai/canarygan/inception/is_score \
    --n_samples 50000 \
    --latent_dim 3 \
    --n_split 10 \
    --batch_size 100 \
    -G "$SLURM_NTASKS_PER_NODE" \
    -c "$SLURM_CPUS_PER_TASK" \
    -N "$SLURM_JOB_NUM_NODES" \

echo "Done !"
