#!/usr/bin/env bash
#SBATCH -J optim_ridge
#SBATCH --constraint="intel"
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --array=0-20
#SBATCH --time=20:00:00
#SBATCH --output=slurm/stdout/optim_ridge-%A-%a.out
#SBATCH --mail-type=END
#SBATCH --mail-user=nathan.trouvain@inria.fr

set -e

echo "Loading modules"
module load compiler/cuda/11.7
module load language/python/3.9.6

echo "=========Python setup========="
echo "python : $(python3 --version), $(which python3)"
echo "pip    : $(pip3 --version), $(which pip3)"

echo "venv activation"
source ./venv/bin/activate

echo "(venv) python : $(python3 --version), $(which python3)"
echo "(venv) pip    : $(pip3 --version), $(which pip3)"

tmpdir="/beegfs/ntrouvai/canarygan/tmp-($hostname)"
mkdir -p "$tmpdir"
export TMP=$tmpdir

srun python3 optimize_decoder.py optim_ridge \
  --preprocessed_dir /beegfs/ntrouvai/canarygan/decoder_ckpt \
  --n_trials 50 \
  --n_instances 30 \
  --storage /beegfs/ntrouvai/canarygan/optuna.log \
  --instance_dir /beegfs/ntrouvai/canarygan/reservoirs \
