#!/usr/bin/env bash
#SBATCH -J umap
#SBATCH --constraint="intel"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=12
#SBATCH --array=0-8:2
#SBATCH --time=24:00:00
#SBATCH --output=slurm/stdout/umap-%A-%a.out
#SBATCH --mail-type=END
#SBATCH --mail-user=nathan.trouvain@inria.fr

set -e

echo "Loading modules"
module load compiler/cuda/11.7
module load language/python/3.9.6

echo "=========Python setup========="
echo "python : $(python3 --version), $(which python3)"
echo "pip    : $(pip3 --version), $(which pip3)"

echo "venv activation"
source ./venv/bin/activate

echo "(venv) python : $(python3 --version), $(which python3)"
echo "(venv) pip    : $(pip3 --version), $(which pip3)"

instances=( 1 5 8 9 13 14 16 18 )
t=$((SLURM_ARRAY_TASK_ID))

for e in 014 029 044 149 299 314 449 554 614 704 809 899 989; do
  for i in $(seq 0 1); do
      idx=$((t+i)) && \
      gidx="${instances[$idx]}" && \
      srun -n1 -c12 python plot_umap.py \
          --gen_dir "/beegfs/ntrouvai/canarygan/generation" \
          --data_dir "/beegfs/ntrouvai/canarygan/dataset" \
          --epoch $e \
          --version "$gidx" \
          --save_dir "/beegfs/ntrouvai/canarygan/umap" \
          --reducer_ckpt "/beegfs/ntrouvai/canarygan/umap-reducer.pkl" \
      &
    done
    wait
done

echo "Done !"
